name: CI/CD Pipeline

# Specifies the events that trigger the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop # You can also add other branches here

jobs:
  lint:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Show working directory
      run: |
        echo "GitHub workspace: $GITHUB_WORKSPACE"
        pwd
        ls -la
        echo "Current user: $(whoami)"
        echo "Docker version: $(docker --version)"
        echo "Docker info: $(docker info)"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint code
      run: |
        flake8 . --exit-zero --statistics > flake8_stats.txt
        error_count=$(grep -oP '^\d+' flake8_stats.txt | awk '{s+=$1} END {print s}')
        if [ "$error_count" -ge 10 ]; then
            echo "Linting failed with $error_count errors."
            exit 1
        else
            echo "Linting passed with $error_count errors."
        fi

  test:
    runs-on: self-hosted
    needs: lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn joblib mlflow dvc

    - name: Prepare data and train model
      run: |
        # dvc pull --force
        python prepare_data.py
        python train_model.py