retrain_model:
  runs-on: self-hosted
  needs: test
  if: ${{ github.event_name == 'push' }}
  steps:
    - name: Check if CSV changed
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'data/breast_cancer.csv'; then
          echo "CSV file changed — retraining."
        else
          echo "No CSV change — skipping."
          exit 0
        fi
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn joblib mlflow dvc
    - name: Retrain model on new data
      run: |
        python prepare_data.py
        python train_model.py
